#!/bin/sh

# map escape to caps lock for vim
setxkbmap -option caps:escape &

# monitor refresh rate
xrandr -r 85 &

dunst &
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources &

# (hardcoded) monitor setup
# python3 ${XDG_CONFIG_HOME:-$HOME/.config}/mon_setup/setup.py &
xrandr --output eDP-1 --mode 1920x1080 --pos 960x1600 --rotate normal --auto --output HDMI-1 --mode 3840x1600 --pos 0x0 --rotate normal --auto

# set background, custom script
setbg

# Wait until the processes have been shut down
redshift -P &
pkill picom &
while pgrep picom >/dev/null; do sleep 1; done; picom &

# startup message
notify-send "everything is done" "startup/restart completed"
